version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    tty: true
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=gmoulard@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - '--providers.file.directory=/dynamic_conf/'
      - '--entrypoints.websecure.http.tls.certresolver=myresolver'
    ports:
      - "80:80"
      - "443:443"
        # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic_conf:/dynamic_conf"